config/routes.rb
Rails.application.routes.draw do
  resources :microposts do
    collection { post :import}
  end

  root to: 'home#index'
  get 'status' => 'status#index'

  get 'admin' => 'admin#index'
  get 'admin/:id/edit' => 'admin#edit', :as => 'admin_edit'
  post 'admin/:id' => 'admin#update'

 
  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }

end

app/views/admin/edit.html.erb
<div id="registration" class="container">
  <div class="row">
    <h1>Edit User Role</h1>
    <p>Is&nbsp;<%= @user.email %>&nbsp;and admin?&nbsp;<strong><%= @user.admin ? "Yes" : "No" %></strong>

    <form action="/admin/<%= @user.id %>" method="post">
      <%= authenticity_token_tag %>

      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@user.errors.count, "error") %> Prohibited this admin from being added:</h2>

          <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <label>Admin</label>
        <input type="checkbox" name="user[admin]" value="true" <%= "checked=\"checked\"" if @user.admin %> />
        <input type="hidden" name="user[id]" value="<%= @user.id %>" />
      </div>

      <input type="submit" class="btn btn-danger"/>
    </form>
  </div>
</div>

app/views/admin/index.html.erb
<div class="admin container">
  <h1>Admin Panel</h1>
  <div class="row">
    <table class="table table-striped">
      <tr>
        <td><b>User Name</b></td>
        <td><b>Email Address</b></td>
        <td><b>Admin</b></td>
        <td></td>
      </tr>
      <% @users.each do |user| %>
          <tr>
            <td><%= user.first_name %>&nbsp;<%= user.last_name %></td>
            <td><%= user.email %></td>
            <td><%= user.admin ? "Yes" : "No" %></td>
            <td><%= link_to '<i class="fa fa-pencil-square-o"></i> Edit'.html_safe, admin_edit_path(user), :class => "btn btn-default" %></td>
          </tr>
      <% end %>
    </table>
  </div>
  <div class='row'>
    <div class="paginate col-lg-12">
      <%= will_paginate @users, :container => false, :params => { :search_text => params[:search_text] }, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
</div>