config/routes.rb
Rails.application.routes.draw do
  resources :microposts do
    collection { post :import}
  end

  root to: 'home#index'
  get 'status' => 'status#index'

  get 'admin' => 'admin#index'
  get 'admin/:id/edit' => 'admin#edit', :as => 'admin_edit'
  post 'admin/:id' => 'admin#update'

 
  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }

end

app/views/partials/_footer.html.erb
<div class="container main">
  <div class="row">
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6">
      <p>© 2014 Barnabas Health<p>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 tos">
      <a href="https://s3.amazonaws.com/myfangate.com/drsday/drsdaytos.pdf" target="_blank"><p>Terms of Service<p></a>
    </div>
  </div>
</div>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <% if user_signed_in? %>
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      <% end %>
      <a class="navbar-brand" href="/"><img src="https://s3.amazonaws.com/myfangate.com/ilovemydoctor/branding.png" alt=""></a>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <p class="navbar-text pull-right">
      <% if user_signed_in? %>
        Logged in as <strong><%= current_user.first_name %>&nbsp<%= current_user.last_name %></strong>
        <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn btn-danger'  %>
      <% else %>
        <a class="btn btn-primary facebookbtn hidden-xs" href="/users/auth/facebook"><i class="fa fa-facebook-square"></i>Sign in with Facebook</a>
      <% end %>
      <% if admin? %>
        <%= link_to '<i class="fa fa-cog"></i>'.html_safe, admin_path, :class => 'btn btn-primary'  %>
      <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>