config/routes.rb
Rails.application.routes.draw do
  resources :microposts do
    collection { post :import}
  end

  root to: 'home#index'
  get 'status' => 'status#index'

  get 'admin' => 'admin#index'
  get 'admin/:id/edit' => 'admin#edit', :as => 'admin_edit'
  post 'admin/:id' => 'admin#update'

 
  devise_for :users, :controllers => { registrations: 'registrations', :omniauth_callbacks => "users/omniauth_callbacks" }

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authorize, :except => :index
  
  def index
    if params[:search]
      @microposts = Micropost.search(params[:search]).order("created_at DESC").paginate(:page => params[:page], :per_page => 10)
    else
      @microposts = Micropost.all.order('created_at DESC').paginate(:page => params[:page], :per_page => 10)
    end
  end
  
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div id="main" class="container">
  <div class="row">
    <div class="col-lg-12 main-logo">
      <img class="img-responsive" src="https://s3.amazonaws.com/myfangate.com/drsday/banner.jpg">
    </div>
    <br>
    <div class="col-lg-12 visible-xs text-center">
      <% if !user_signed_in? %>
        <a class="btn btn-primary facebookbtn lg-fb" href="/users/auth/facebook"><i class="fa fa-facebook-square"></i>Sign in with Facebook</a>
      <% end %>
    </div>
    <div id="searchzone" class="col-lg-12">
      <%= link_to '<i class="fa fa-pencil"></i>Click Here To Thank Your Doctor'.html_safe, new_micropost_path, :class => "btn btn-success main-cta"  %>
      <%= form_tag root_path, :method => :get do %>
      <i class="fa fa-search"></i>
      <%= text_field_tag :search, params[:search], placeholder: 'Search for your doctor...', :class => "input-lg"  %>
      <%= submit_tag "Search", :name => nil, :class => "btn btn-primary" %>
      <% end %>
    </div>
    <% if current_user =  admin? %>
      <div class="col-lg-6 col-lg-offset-3 col-md-6 col-md-offset-3 col-sm-6 col-sm-offset-3 col-xs-6 col-xs-offset-3 csv-upload">
        <h3>Import a CSV File</h3>
        <%= form_tag import_microposts_path, multipart: true do %>
        <%= file_field_tag :file, :class=> "importfield" %>
        <%= submit_tag "Import CSV", :class=> "btn btn-default" %>
        <% end %>
      </div>
    <% end %>
  </div>
  <br>
    <div class="row indexh1">
      <h1>What people are saying:</h1>
    </div>
    <br>
    <div class="row">
    <% @microposts.each do |micropost| %>
      <div class="micropost" data-id="<%= micropost.id %>">
        <div class="bubble">
          <h4>To: <%= micropost.drname %></h4>
          <p><%= micropost.content %></p>
        </div>
        <br>
        <div class="userandbuttons">
          <% if micropost.user == nil %>
            <p class="usertext"><i class="fa fa-user"></i><%= micropost.first_name %> <%= micropost.last_name %><p>
          <% else %>
            <p class="usertext"><i class="fa fa-user"></i><%= micropost.user.first_name %> <%= micropost.user.last_name %><p>
          <% end %>
          <p class="buttongroup">
            <a class="btn btn-primary fb-share facebookbtn2"><i class="fa fa-facebook-square"></i> Share</a>
            <%= link_to '<i class="fa fa-eye"></i> View'.html_safe, micropost, :class => "btn btn-success" %>
            <% if user_signed_in? && (micropost.user == current_user || admin?) %>
              <%= link_to '<i class="fa fa-pencil-square-o"></i> Edit'.html_safe, edit_micropost_path(micropost), :class => "btn btn-default" %>
              <%= link_to '<i class="fa fa-trash-o"></i> Delete'.html_safe, micropost, :class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %>
            <% end %>
          </p>
        </div>
      </div>
    <% end %>
    <br>
    </div>

  <div class='row'>
    <div class="paginate col-lg-12">
      <%= will_paginate @microposts,:inner_window => 2, :outer_window => 2, :container => false, :params => { :search_text => params[:search_text] }, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
</div>